

# This file was *autogenerated* from the file field.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_30 = Integer(30)# Prime field
p = _sage_const_3 *(_sage_const_1 <<_sage_const_30 ) + _sage_const_1 
Fp = GF(p, modulus='primitive', names=('w',)); (w,) = Fp._first_ngens(1)# Defining a prime field with generator w

